apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-i2xk
  namespace: samburrai-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:440e9833c960c5204ee96dfd6dc9b385b6eea2afc0a005b533582063b0eff6a7
        name: my-python
        resources: {}
status: {}
